title: "Lacona Blog"
description: "Updates about Lacona development, and general musings about natural language UX and Apple development."
url: https://lacona.app/blog
author:
  twitter: brandonhorst
plugins:
  - jekyll-feed